name: instagram_clone
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  blurrycontainer: 1.0.2
  dotted_border: ^2.0.0+2
  flutter_svg: ^1.1.5
  flutter_staggered_grid_view: ^0.6.2

  flutter_lorem: ^2.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
  

  
  fonts:
    - family: GR
      fonts:
        - asset: fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: fonts/GilroyMedium.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: fonts/GilroyExtraBold.ttf
          weight: 800
          
    - family: GH
      fonts:
        - asset: fonts/GilroyHeavy.ttf
          weight: 900

    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf
          weight: 500
  
