name: monews_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  marquee: ^2.2.3
  carousel_slider: ^4.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf
