name: note_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  msh_checkbox: ^1.1.1
  roundcheckbox: ^2.0.5
  day_night_time_picker: ^1.1.3

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf
          weight: 500
